### ISSUE TITLE
(💡) 

### ISSUE THREAD

**Issue by alexandros007** [DorrD/DorrDPack#11]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.** (opcional)
no

**Describe la solución que te gustaría**
pues me gustaria que añadieran otra vez la flecha que indicaba que los cultivos estaban crecidos y tambien lo de la comida que da cada alimento 

**Nota adicional** (opcional)
ojala lo pongan ya que me ayudaba mucho a saber que cultivos estaban crecidos y a saber que comidas son mejores nwn

**Comment by Esteor0tip0** [comment]
Ya estoy notificado de ello, y se considera un error. Se arreglará en la próxima versión del "DorrD Pack Survival".
