### ISSUE TITLE
[👍 SUGERENCIA] Texture Pack con varias versiones de colores de Slime

### ISSUE THREAD

**Issue by DorrD** [DorrD/DorrDPack#6]
**Describe la solución que te gustaría**
Que los slimes tuviesen varios colores. Por ejemplo, que haya una versión de slime rojo, morado, negro... etc.
Ya que hay gente, que seguro que le gustaría.

**Comment by Esteor0tip0** [comment]
Por ahora, no creo que se añade esa función. Ya que es muy costoso.
