### ISSUE TITLE
(⛔) Enderman sin texturas

### ISSUE THREAD

**Issue by alexandros007** [DorrD/DorrDPack#9]
**Descripción del error**
Los endermans estan bugeados se les ve bastante raros

**Capturas** (opcional)
![2021-07-02_13 50 24](https://user-images.githubusercontent.com/34277998/124280019-78751780-db48-11eb-9d53-0861f53cd62c.png)
![2021-07-02_13 49 55](https://user-images.githubusercontent.com/34277998/124280022-79a64480-db48-11eb-8940-4b7b1b5525ee.png)

**Información técnica**
 - Minecraft Version 1.17
 - Versión 0.8

**Nota adicional** (opcional)
[Tu mensaje aquí]

**Comment by Esteor0tip0** [comment]
Por favor, prueba lanzar tu Minecraft sin Optifine. Y comenta, que es lo que ocurre.

**Comment by alexandros007** [comment]
hola, acabo de entrar sin optifine y se ven bien, así que debe ser cosa de optifine

**Comment by Esteor0tip0** [comment]
Prueba entrar con Optifine, y a un mundo en solitario.

**Comment by alexandros007** [comment]
acabo de comprobarlo y salen como en la foto que mande del reporte

**Comment by alexandros007** [comment]
a lo mejor es por la version de optifine 
que uso una poco anterior

**Comment by alexandros007** [comment]
puede ser por eso

**Comment by Esteor0tip0** [comment]
En caso que siga con las versiones más recientes, pásame el log del Minecraft, donde se vea el proceso de carga de texturas.
Ya que no estoy experimentando ese error, y por ahora no hemos recibido ningún problema parecido a lo suyo.

**Comment by alexandros007** [comment]
con la ultima version de optifine (OptiFine HD U G9 pre24) me sigue pasando, ahora te mando los logs

**Comment by alexandros007** [comment]
[latest.log](https://github.com/DorrD/DorrDPack/files/6758320/latest.log)

**Comment by Esteor0tip0** [comment]
@alexandros007 parece que tu ordenador no puede leer el archivo del modelo personalizado JEM del Enderman. Puede ser lo siguiente:
- **PC no compatible con JEM**: en este caso no hay solución, y lo único es que quites un archivo de ese modelo.
- **Java 16**: Desde la 1.17, Minecraft recomienda el uso de Java 16 para la carga optimizada de chunks y podría tu PC leer el archivo JEM de Enderman. [Descargar Java 16 Oficial](https://www.oracle.com/java/technologies/javase-jdk16-downloads.html)

Pruebe y haber si se encuentra esa solución.

**Comment by alexandros007** [comment]
voy a probar con lo de java16 ahora te cuento si me sigue pasando

**Comment by alexandros007** [comment]
me sigue pasando con lo de java16

**Comment by Esteor0tip0** [comment]
Vale, haz lo siguiente:

1. Windows+R
2. Escribir %appdata%
3. Busca una carpeta que se llama ".minecraft"
4. Busca otra carpeta llamada "resource packs"
5. Te saldrá una lista de paquetes de texturas instaladas en tu dispositivo, busca el "DorrD Pack Survival 0.8.0v"
6. **A partir de aquí requieres WinRar** Abre el archivo del paquete de texturas.
7. **En WinWar** Abre la carpeta "assets"
8. **En WinWar** Abre la carpeta "minecraft"
9. **En WinWar** Abre la carpeta "optifine"
10. **En WinWar** Abre la carpeta "cem"
11. **En WinWar** Borra el archivo "enderman.jen"

Instalar WinRar: [https://www.winrar.es/descargas](https://www.winrar.es/descargas)

**Recuerda:** Por lo menos en la **0.8** tendrás que hacer siempre estos pasos por cada actualización. Y además, si tienes otro problema, reporta como hiciste. Se agradece, para mantener el paquete de texturas libre de bugs y crasheos en su versión final. ¡Gracias por tu reporte!
